set -g history-limit 100000
set -g mouse on
set -g escape-time 10
set -g focus-events on

set -g default-terminal screen-256color
set -g status-fg colour246
set -g status-bg colour232

set -g status-left "#[fg=colour244,bg=colour236] #S "
set -g status-right "#[fg=colour244,bg=colour236] %Y-%m-%d #[fg=colour232]|#[fg=colour244] %H:%M "
setw -g window-status-format "#[fg=colour242,bg=colour232]  #I:#W  "
setw -g window-status-current-format "#[fg=colour232,bg=colour240]  #I:#W  "

set -g prefix C-a
bind-key C-a send-prefix
