#!/usr/bin/bash

# Create subfolders if doesn't exist
mkdir -p bin/   # Save essential binaries (like bash) here
mkdir -p root/  # Root user folder
mkdir -p proc/  # System folder to be mounted
mkdir -p sys/   # System folder to be mounted
mkdir -p dev/   # System folder to be mounted
mkdir -p tmp/   # System folder to be mounted

# Mount system folders
sudo mount -t proc /proc proc/
sudo mount -t sysfs /sys sys/
sudo mount -t tmpfs /tmp tmp/
sudo mount --rbind /dev dev/

# Initialize chroot
PS1='\$ \w ' sudo chroot .

# Umount system folders
sudo umount -R proc/
sudo umount -R sys/
sudo umount -R tmp/
sudo umount -R dev/
