#!/usr/bin/bash

__MANPATH=$MANPATH
__CPATH=$CPATH
__LD_LIBRARY_PATH=$LD_LIBRARY_PATH
__LIBRARY_PATH=$LIBRARY_PATH
__PKG_CONFIG_PATH=$PKG_CONFIG_PATH
__PATH=$PATH

loadenv() {
  local PREFIX=`realpath $1`
  export MANPATH="$PREFIX/share/man:$MANPATH"
  export CPATH="$PREFIX/include:$CPATH"
  export LD_LIBRARY_PATH="$PREFIX/lib:$LD_LIBRARY_PATH"
  export LIBRARY_PATH="$PREFIX/lib:$LIBRARY_PATH"
  export PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
  export PATH="$PREFIX/bin:$PATH"
}

unloadenv() {
  export MANPATH=$__MANPATH
  export CPATH=$__CPATH
  export LD_LIBRARY_PATH=$__LD_LIBRARY_PATH
  export LIBRARY_PATH=$__LIBRARY_PATH
  export PKG_CONFIG_PATH=$__PKG_CONFIG_PATH
  export PATH=$__PATH
  unset __MANPATH
  unset __CPATH
  unset __LD_LIBRARY_PATH
  unset __LIBRARY_PATH
  unset __PKG_CONFIG_PATH
  unset __PATH
  unset loadenv
  unset unloadenv
}

[ $1 ] && loadenv $1 
