#!/usr/bin/bash

loadenv() {
  local PREFIX=`realpath $1`

  [ ! $__MANPATH ] && __MANPATH=$MANPATH
  [ ! $__CPATH ] && __CPATH=$CPATH
  [ ! $__LD_LIBRARY_PATH ] && __LD_LIBRARY_PATH=$LD_LIBRARY_PATH
  [ ! $__LIBRARY_PATH ] && __LIBRARY_PATH=$LIBRARY_PATH
  [ ! $__PKG_CONFIG_PATH ] && __PKG_CONFIG_PATH=$PKG_CONFIG_PATH
  [ ! $__PATH ] && __PATH=$PATH

  export MANPATH="$PREFIX/share/man:$MANPATH"
  export CPATH="$PREFIX/include:$CPATH"
  export LD_LIBRARY_PATH="$PREFIX/lib:$LD_LIBRARY_PATH"
  export LIBRARY_PATH="$PREFIX/lib:$LIBRARY_PATH"
  export PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
  export PATH="$PREFIX/bin:$PATH"
}

unloadenv() {
  [ -v __MANPATH ] && export MANPATH=$__MANPATH
  [ -v __CPATH ] && export CPATH=$__CPATH
  [ -v __LD_LIBRARY_PATH ] && export LD_LIBRARY_PATH=$__LD_LIBRARY_PATH
  [ -v __LIBRARY_PATH ] && export LIBRARY_PATH=$__LIBRARY_PATH
  [ -v __PKG_CONFIG_PATH ] && export PKG_CONFIG_PATH=$__PKG_CONFIG_PATH
  [ $__PATH ] && export PATH=$__PATH

  unset __MANPATH
  unset __CPATH
  unset __LD_LIBRARY_PATH
  unset __LIBRARY_PATH
  unset __PKG_CONFIG_PATH
  unset __PATH

  [ ! $MANPATH ] && unset MANPATH
  [ ! $CPATH ] && unset CPATH
  [ ! $LD_LIBRARY_PATH ] && unset LD_LIBRARY_PATH
  [ ! $LIBRARY_PATH ] && unset LIBRARY_PATH
  [ ! $PKG_CONFIG_PATH ] && unset PKG_CONFIG_PATH
}

[ $1 ] && loadenv $1 
