#!/usr/bin/bash

# Create a folder, download Alpine Linux MINI ROOT FILESYSTEM and unpack
# Save this file in that folder and run

sudo mount -o bind /dev dev/
sudo mount -t proc none proc/
sudo mount -o bind /sys sys/
sudo mount -o bind /tmp tmp/

cp -L /etc/resolv.conf etc/
xhost + local: > /dev/null

sudo chroot . sh -l

sudo umount -R {dev/,proc/,sys/,tmp/}
